%% Generate 3D GRE sequence
gre3d_write_seq('N', 128, ...
    'fov', 20, ...
    'fa', 6, ...
    'tr', 15, ...
    'te', 'min', ...
    'Nacs', 32, ...
    'Ry', 2, ...
    'Rz', 2);

%% Convert the 3D GRE scanarchive data to custom h5 file format
% Assumed that the scanarchive file is transferred into the gre directory
gre3d_convert_data('gre3d_scanarc.h5', './gre3d_data.h5');

%% Generate LpS sequence
lps_write_seq('N', 100, ...
    'fov', 20, ...
    'fa', 6, ...
    'tr', 62.5, ...
    'nprj', 320);

%% Convert the LpS scanarchive data to custom h5 file format
% Assumed that the scanarchive file is transferred into the working directory
lps_convert_data('./lps_scanarc.h5', './lps_data.h5');
