function sys = get_sys_defaults(vendor,varargin)
% returns pulseq system structure with defaults for given vendor
% by David Frey (djfrey@umich.edu)
%
% inputs:
% vendor - 'ge' or 'siemens'
% varargin - extra system modifiers
%
% outputs:
% sys - pulseq system structure
%

	switch lower(vendor)
		case 'ge'
			sys = mr.opts('MaxGrad', 50, 'GradUnit', 'mT/m', ...
				'MaxSlew', 170, 'SlewUnit', 'mT/m/ms', ...
				'rfDeadTime', 100e-6, ...
				'rfRingdownTime', 160e-6, ...
				'adcRasterTime', 4e-6, ...
				'gradRasterTime', 4e-6, ...
				'rfRasterTime', 2e-6, ...
				'blockDurationRaster', 4e-6, ...
				'B0', 3, ...
				'adcDeadTime', 0e-6, ...
                varargin{:});
		case 'siemens'
            % Siemens Vida 3T specs from Tom Griesler
			sys = mr.opts( ...
                'B0', 3, ...
                'maxGrad', 43, 'GradUnit', 'mT/m', ...
                'maxSlew', 180, 'SlewUnit', 'T/m/s', ...
                'maxB1', mr.convert(20,'uT'), ...
                'rfDeadTime', 1e-4, ...
                'rfRingdownTime', 1e-4, ...
                'adcDeadTime', 1e-5, ...
                'adcRasterTime', 1e-7, ...
                'rfRasterTime', 1e-6, ...
                'gradRasterTIme', 1e-5, ...
                'blockDurationRaster', 1e-5, ...
                 varargin{:});
		otherwise
			error('invalid vendor');
	end

end
